apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z2e8h8wi3-python 
  janus-idp.io/tekton: z2e8h8wi3-python
  backstage.io/kubernetes-id: z2e8h8wi3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2e8h8wi3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml